version: '3'
services:
  # リバースプロキシ
  #proxy:
  #  image: jwilder/nginx-proxy
  #  container_name: nuxt2-docker-jwilder-nginx-proxy
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./nginx.conf /etc/nginx/conf.d/nginx.conf
  #  network_mode: "bridge"
  #  restart: always
  proxy:
    build: ./proxy
    container_name: "nuxt2-docker-nginx-proxy"
    ports:
        - 80:80
  # Nuxt.js
  web:
    build: ./web
    # volumes:
    #  - "./:/app" # ホストの./をdocker内に/appへマウント
    ports:
      - "3000:3000"
    restart: always # コンテナ停止時の挙動. always: 明示的に stop がされない限り、終了ステータスに関係なく常に再起動が行われる
    container_name: "nuxt2-docker"
    tty: true # 永続化
